OZ-162: Add Option to run behind Traefik
ozone-his/ozone-docker pull request #38
Opened 2023-04-26 04:56 UTC by enyachoke

2023-04-29 17:58 UTC, imbuchi approved these changes

2023-05-01 09:47 UTC, mks-d commented on README.md
> +# For running behind Traefik see the manual instructions.
This is too verbose for a quick start, I would suggest not writing any of this and just make sure that we come up with a compact set of instructions that work for everyone.

Such details need to be provided in the manual setup guide.

2023-05-01 09:47 UTC, mks-d commented on readme/manual-setup.md
> +### Step 6. Setting up Traefik
So I made this its own step in the setup, however, unlike with the quick start, it is never required to run this:
```bash
docker network create web
```
Is that intended?

2023-05-03 07:03 UTC, mks-d requested changes

2023-05-03 07:03 UTC, mks-d commented on README.md
> +
Nope, the quick start guide needs to lead to **one** clear outcome, options and choice subtleties are left to the manual setup.
(Btw you have left a typo in each of the Traefik URLs.)

So, we need to choose what the quick start achieves by default, and make it do just that.

2023-05-04 09:06 UTC, rbuisson commented
@enyachoke , is that a breaking change for people who currently deploy with Ozone Docker?

2023-05-04 10:58 UTC, enyachoke commented
> [enyachoke](https://github.com/enyachoke) , is that a breaking change for people who currently deploy with Ozone Docker?
Yes, we just can't have support for both so they will need to make some changes.

2023-05-05 10:16 UTC, rbuisson commented
In that case, we need to change the version number isn't it? I'm a bit concerned that all of a sudden the Ozone Distro Kh deployments will stop working.
I'm not saying we should release `1.0.0` though. Might want to keep a `1.x` branch for reference and upgrade to `2.0.0-SNAPSHOT` directly.

Does that sounds OK @enyachoke ?

2023-05-05 10:28 UTC, merged